### PR TITLE
clear output and minor fix on notebooks

### PR DESCRIPTION
**Pull request by roywei**
## Channel for questions ##

1. cleared outputs.
2. use 0.7.0 snapshot for consistency
3. minor update on install command line.

Before or while filing an issue please feel free to join our [Slack channel](https://join.slack.com/t/deepjavalibrary/shared_invite/enQtODAwOTg0OTUzNDEwLTdlY2M4NmNlZTMzM2Q4MDUyZThkYzQwNmE2MDVhNTRiZDcxNTNlMWJhNTZkNWE1OGU2Nzg3MmY1OWQzN2Q5Mzk) to get in touch with development team, ask questions, find out what's cooking and more!

## Description ##
(Brief description of what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- [ ] Code is well-documented: 
    - For user-facing API changes, Java doc has been updated. 
    - For new examples, README.md is added to explain the what the example does.
- [ ] To the my best knowledge, [examples](https://github.com/awslabs/djl/tree/master/examples) and [jupyter notebooks](https://github.com/awslabs/djl/tree/master/jupyter) are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, Java doc)
- [ ] Feature2, tests, (and when applicable, Java doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made?
- Interesting edge cases to note here

### CODE REVIEW

**Comment by lanking520** [comment]
Could you please fix `dropout.ipynb` as well?

**Comment by roywei** [comment]
> Could you please fix `dropout.ipynb` as well?

the notebook is running file local, maybe github pull a wrong/cached version of 0.7.0 snapshot.

**Comment by lanking520** [comment]
> > Could you please fix `dropout.ipynb` as well?
> 
> the notebook is running file local, maybe github pull a wrong/cached version of 0.7.0 snapshot.

Just double checked
```
        /**
         * Sets the probability or the fraction of the input that gets dropped out during training
         * time. Defaults to 0.5.
         *
         * @param rate fraction of the input that gets dropped out during training
         * @return this Builder
         */
        public Builder optRate(float rate) {
            this.rate = rate;
            return this;
        }
```

**Comment by roywei** [comment]
> > > Could you please fix `dropout.ipynb` as well?
> > 
> > 
> > the notebook is running file local, maybe github pull a wrong/cached version of 0.7.0 snapshot.
> 
> Just double checked
> 
> ```
>         /**
>          * Sets the probability or the fraction of the input that gets dropped out during training
>          * time. Defaults to 0.5.
>          *
>          * @param rate fraction of the input that gets dropped out during training
>          * @return this Builder
>          */
>         public Builder optRate(float rate) {
>             this.rate = rate;
>             return this;
>         }
> ```

yes, updated.

**Pull request merged**
